os: linux
dist: xenial
sudo: true
language: python

env:
  global:
    - TWINE_USERNAME=astroduff
    - secure: "hAv1a07lo6B/T/z3+kt4iwvBb3GgT9kUPiKFgjCaVo/qpDWCSsddhwEClr+YwlqhSoGOyP6iEcbmE7HpZ5BKwgoBKdDkPxFZOP6DH7ZGEW4xTrEItSfhgOIyV0sOThTnA5EUv1xh9UQ1GD7WOf1ZYIl2zxadgj+cD0BmEkOfOhr7/c393rUPplfwc20ZJpyesmlxBnAZRIAd9T61uIQKsRN3w0e47G+OWKM8ykwkqsHGQCJV+3C1wHnmtoQyoCpFVq3tlJCQ/cA8UGyljap8cd3+Qp3CoXl9LngvKJS9ojA3cUj1+gZxAz5Jk3jkZlJoqIFM/mu0i/wHXgwKUsd9YJ0huqvnKusS5HAv8a12kYE+L/3oLNbMOrdtSdS1/LmugfLiSdeDMjsas8IRckP3qNPXDPfC5+7CGr2lA3ZxlJeGb4HjWHtbTZLLeGVGB8YuaTZEao+2RuYqR1FYQlIQsEtU8AQ5dQ0EPVPk2e+7N5nabt6InksWBLGu9jZPZCIauKvGgqeC77wZOymKPCawE6lgnwp8ItYL9jC2BtckaFRdVEl/1yySn7wmMnIaQHQRAEmsxe2DcPjnHN2wjbss7OcT8NegTGQTwajQ1lt7yjFqSLlNsZBgK894bK8SrZrYcIIg9WVBWqPuP9NGOGGlLIk6ujuvFfGy2eRqvvi7FPs="

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.17 PY=2.7
    - os: osx
      language: generic
      env: PYTHON=3.5.8 PY=3.5
    - os: osx
      language: generic
      env: PYTHON=3.6.9 PY=3.6
    - os: osx
      language: generic
      env: PYTHON=3.7.9 PY=3.7
    - os: osx
      language: generic
      env: PYTHON=3.8.8 PY=3.8
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull $DOCKER_IMAGE
    else
      brew update
      brew cleanup
      brew install pyenv
      brew upgrade pyenv
      eval "$(pyenv init -)"
      brew install swig
      pyenv install $PYTHON
      pyenv global $PYTHON
      python$PY -m pip install --upgrade pip setuptools wheel
      pip$PY install -r requirements.txt
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
    else
      python$PY setup.py sdist -d wheelhouse
      pip$PY wheel . -w wheelhouse
      cd wheelhouse
      pip$PY install cosmolopy --no-index -f .
      python$PY -c "import cosmolopy; import cosmolopy.EH.power"
      cd ..
    fi

after_success:
  - pip$PY install twine
  - python$PY -m twine upload --skip-existing wheelhouse/cosmolopy*
